**Soru-1**

1'den 200'ye kadar olan çift sayılardan oluşan 10 X 10'luk bir dizi oluşturun. arange() fonksiyonu yardımcı olabilir.

**Cevap-1**

In [1]:
import numpy as np

In [35]:
tamdizi = np.arange (1, 201)

ciftdizi = tamdizi [tamdizi%2==0]
                    
ciftdizi

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [44]:
karedizi = ciftdizi.reshape (10,10)

karedizi

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100],
       [102, 104, 106, 108, 110, 112, 114, 116, 118, 120],
       [122, 124, 126, 128, 130, 132, 134, 136, 138, 140],
       [142, 144, 146, 148, 150, 152, 154, 156, 158, 160],
       [162, 164, 166, 168, 170, 172, 174, 176, 178, 180],
       [182, 184, 186, 188, 190, 192, 194, 196, 198, 200]])

**Soru-2**

Parametre olarak girilen satır ve kolon sayısına göre kenarları 1'lerden, içi 0'lardan oluşan dizi döndüren bir fonksiyon yazınız.

**Cevap-2**

In [46]:
def k1i0dizi (x, y):
    kenar = np.ones((x, y))
    kenar[1:-1, 1:-1] = 0
    print(kenar)
    
k1i0dizi (8, 10)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
